import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { uniqueStrings } from "./businessText.js";
import { productIconDataUri, productIconSvg, productName } from "./product.js";
import type {
  ConcernArea,
  ExternalEvidence,
  PageLastModifiedEvidence,
  ReportPaths,
  ReviewConcern,
  ReviewResult,
  SiteIdentityReview,
  UrlVariantCheck
} from "./types.js";

export async function writeReports(result: ReviewResult, outputDir: string): Promise<ReportPaths> {
  await mkdir(outputDir, { recursive: true });

  const paths: ReportPaths = {
    outputDir,
    markdown: path.join(outputDir, "report.md"),
    html: path.join(outputDir, "report.html"),
    summaryHtml: path.join(outputDir, "summary.html"),
    summaryText: path.join(outputDir, "client-summary.txt"),
    checklistMarkdown: path.join(outputDir, "follow-up-checklist.md"),
    evidenceJson: path.join(outputDir, "evidence.json"),
    screenshotsDir: path.join(outputDir, "screenshots")
  };

  await Promise.all([
    writeFile(paths.markdown, renderMarkdown(result), "utf8"),
    writeFile(paths.html, renderFullHtml(result), "utf8"),
    writeFile(paths.summaryHtml, renderSummaryHtml(result), "utf8"),
    writeFile(paths.summaryText, renderPlainSummary(result), "utf8"),
    writeFile(paths.checklistMarkdown, renderChecklistMarkdown(result), "utf8"),
    writeFile(paths.evidenceJson, `${JSON.stringify(result, null, 2)}\n`, "utf8")
  ]);

  return paths;
}

function renderMarkdown(result: ReviewResult): string {
  const { evidence, concerns, summary } = result;
  const lines = [
    `# ${productName}`,
    "",
    `Website: ${evidence.input.websiteUrl}`,
    evidence.input.companyName ? `Company name provided: ${evidence.input.companyName}` : undefined,
    evidence.input.claimedLocation ? `Location provided: ${evidence.input.claimedLocation}` : undefined,
    evidence.input.expectedState ? `Expected state provided: ${evidence.input.expectedState}` : undefined,
    evidence.input.claimedIndustry ? `Industry/service provided: ${evidence.input.claimedIndustry}` : undefined,
    evidence.input.additionalIdentifiers ? `Additional identifiers provided: ${evidence.input.additionalIdentifiers}` : undefined,
    `Started: ${evidence.startedAt}`,
    `Pages reviewed: ${evidence.pages.length}`,
    `Review outcome: ${summary.riskLevel}`,
    `Concern level: ${summary.concernLevel}`,
    `Confidence: ${summary.confidence}`,
    `Likely official website: ${summary.likelyOfficialWebsite}`,
    "",
    "## Executive Summary",
    "",
    ...bulletList(executiveSummary(result)),
    "",
    "## Decision Brief",
    "",
    ...renderDecisionBriefMarkdown(result),
    "",
    "## Visible Conclusion",
    "",
    ...renderVisibleConclusionMarkdown(result),
    "",
    "## Verified Facts",
    "",
    ...bulletList(summary.verifiedFacts),
    "",
    "## Positive Indicators",
    "",
    ...bulletList(summary.positiveIndicators),
    "",
    "## Concerns And Indicators",
    "",
    ...bulletList(summary.concernIndicators.length ? summary.concernIndicators : ["No priority concern indicators were generated by the built-in checks."]),
    "",
    "## Unknown Or Unverified",
    "",
    ...bulletList(summary.unknowns.length ? summary.unknowns : ["No unknown items were generated by the built-in checks."]),
    "",
    "## Final Assessment",
    "",
    ...renderAssessmentMarkdown(result),
    "",
    "## Site Identity Summary",
    "",
    ...renderSiteIdentityMarkdown(result),
    "",
    "## Domain And Page Dates",
    "",
    ...renderDomainDatesMarkdown(result),
    "",
    "## External Evidence",
    "",
    ...renderExternalEvidenceMarkdown(result),
    "",
    "## Category Assessment",
    "",
    ...renderCategoryAssessmentMarkdown(result),
    "",
    "## Priority Follow-Up",
    "",
    ...renderPriorityMarkdown(result),
    "",
    "## Review Snapshot",
    "",
    ...renderSnapshotMarkdown(result),
    "",
    "## Verification Coverage",
    "",
    ...renderCoverageMarkdown(result),
    "",
    "## What Looked Complete",
    "",
    ...bulletList(summary.positiveNotes),
    "",
    "## Needs Follow-Up",
    "",
    ...bulletList(summary.followUpNotes),
    "",
    "## Suggested Next Steps",
    "",
    ...renderChecklistItems(result).map((item) => `- [ ] ${item}`),
    "",
    "## Public Details Found",
    "",
    ...renderSignalsMarkdown(result),
    "",
    "## Concerns By Category",
    ""
  ].filter((line): line is string => line !== undefined);

  if (concerns.length === 0) {
    lines.push("- No concerns were found by the built-in checks.", "");
  } else {
    for (const [area, groupedConcerns] of groupConcerns(concerns)) {
      lines.push(`### ${areaLabel(area)}`, "");
      for (const concern of groupedConcerns) {
        lines.push(`- ${formatConcern(concern)}`);
      }
      lines.push("");
    }
  }

  lines.push("## Pages Reviewed", "");
  for (const page of evidence.pages) {
    const pageEmails = page.details?.emails ?? [];
    const pagePhones = page.details?.phones ?? [];
    lines.push(`### ${page.title || page.finalUrl}`);
    lines.push("");
    lines.push(`- URL: ${page.finalUrl}`);
    lines.push(`- HTTP status: ${page.status ?? "not available"}`);
    lines.push(`- Meta description: ${page.metaDescription || "none found"}`);
    lines.push(`- Last modified: ${page.lastModified ? formatPageLastModified(page.lastModified) : "not available"}`);
    lines.push(`- Headings: ${page.headings?.length ? page.headings.join(" | ") : "none found"}`);
    lines.push(`- Links found: ${page.links.length}`);
    lines.push(`- Emails found: ${pageEmails.length}`);
    lines.push(`- Phones found: ${pagePhones.length}`);
    lines.push(`- Contact forms found: ${page.forms?.contactFormCount ?? 0}`);
    lines.push(`- Screenshot: ${path.relative(evidencePathBase(page.screenshotPath), page.screenshotPath) || page.screenshotPath}`);
    if (page.note) {
      lines.push(`- Note: ${page.note}`);
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

function renderFullHtml(result: ReviewResult): string {
  const { evidence, concerns, summary } = result;
  const concernItems = renderGroupedConcerns(concerns);

  const pageRows = evidence.pages
    .map((page) => {
      const screenshotName = path.basename(page.screenshotPath);
      return `<tr>
        <td><a href="${escapeAttribute(page.finalUrl)}">${escapeHtml(page.title || page.finalUrl)}</a></td>
        <td>${page.status ?? "n/a"}</td>
        <td>${page.metaDescription ? escapeHtml(page.metaDescription) : '<span class="muted">none found</span>'}</td>
        <td>${page.lastModified ? escapeHtml(formatPageLastModified(page.lastModified)) : '<span class="muted">not available</span>'}</td>
        <td>${page.headings?.length ? escapeHtml(page.headings.slice(0, 4).join(" | ")) : '<span class="muted">none found</span>'}</td>
        <td><a href="screenshots/${escapeAttribute(screenshotName)}">${escapeHtml(screenshotName)}</a></td>
      </tr>`;
    })
    .join("\n");

  const gallery = evidence.pages
    .map((page) => {
      const screenshotName = path.basename(page.screenshotPath);
      return `<figure>
        <img src="screenshots/${escapeAttribute(screenshotName)}" alt="${escapeAttribute(page.title || page.finalUrl)}">
        <figcaption><strong>${escapeHtml(page.title || page.finalUrl)}</strong><span>HTTP ${page.status ?? "n/a"}</span></figcaption>
      </figure>`;
    })
    .join("\n");

  return htmlDocument(
    productName,
    `<main class="shell">
      <section class="hero">
        <div class="hero-title">
          <span class="report-mark" aria-hidden="true">${productIconSvg}</span>
          <div>
            <p class="eyebrow">${escapeHtml(productName)}</p>
            <h1>${escapeHtml(readableHost(evidence.input.websiteUrl))}</h1>
            <p>${escapeHtml(evidence.input.companyName ?? "Business website review")}</p>
          </div>
        </div>
        <div class="score">
          <span>${escapeHtml(summary.riskLevel)}</span>
          <small>Confidence: ${escapeHtml(summary.confidence)} | Likely official website: ${escapeHtml(summary.likelyOfficialWebsite)}</small>
        </div>
      </section>

      <section class="metrics">
        ${renderSnapshotHtml(result)}
      </section>

      <section>
        <h2>Decision Brief</h2>
        ${renderDecisionBriefHtml(result)}
      </section>

      <section>
        <h2>Verification Coverage</h2>
        ${renderCoverageHtml(result)}
      </section>

      <section>
        <h2>Executive Summary</h2>
        ${renderList(executiveSummary(result))}
      </section>

      <section>
        <h2>Visible Conclusion</h2>
        ${renderVisibleConclusionHtml(result)}
      </section>

      <section>
        <h2>Verified Facts</h2>
        ${renderList(summary.verifiedFacts)}
      </section>

      <section>
        <h2>Positive Indicators</h2>
        ${renderList(summary.positiveIndicators)}
      </section>

      <section>
        <h2>Concerns And Indicators</h2>
        ${renderList(summary.concernIndicators.length ? summary.concernIndicators : ["No priority concern indicators were generated by the built-in checks."])}
      </section>

      <section>
        <h2>Unknown Or Unverified</h2>
        ${renderList(summary.unknowns.length ? summary.unknowns : ["No unknown items were generated by the built-in checks."])}
      </section>

      <section>
        <h2>Final Assessment</h2>
        ${renderAssessmentHtml(result)}
      </section>

      <section>
        <h2>Site Identity Summary</h2>
        ${renderSiteIdentityHtml(result)}
      </section>

      <section>
        <h2>Domain And Page Dates</h2>
        ${renderDomainDatesHtml(result)}
      </section>

      <section>
        <h2>External Evidence</h2>
        ${renderExternalEvidenceHtml(result)}
      </section>

      <section>
        <h2>Category Assessment</h2>
        ${renderCategoryAssessmentHtml(result)}
      </section>

      <section>
        <h2>Priority Follow-Up</h2>
        ${renderPriorityHtml(result)}
      </section>

      <section>
        <h2>What Looked Complete</h2>
        ${renderList(summary.positiveNotes)}
      </section>

      <section>
        <h2>Needs Follow-Up</h2>
        ${renderList(summary.followUpNotes)}
      </section>

      <section>
        <h2>Suggested Next Steps</h2>
        ${renderChecklistHtml(result)}
      </section>

      <section>
        <h2>Public Details Found</h2>
        ${renderSignalsHtml(result)}
      </section>

      <section>
        <h2>Concerns By Category</h2>
        <div class="concern-list">${concernItems}</div>
      </section>

      <section>
        <h2>Pages Reviewed</h2>
        <div class="table-wrap">
          <table>
            <thead><tr><th>Page</th><th>Status</th><th>Meta Description</th><th>Last Modified</th><th>Headings</th><th>Screenshot</th></tr></thead>
            <tbody>${pageRows}</tbody>
          </table>
        </div>
      </section>

      <section>
        <h2>Screenshots</h2>
        <div class="gallery">${gallery}</div>
      </section>

      <section>
        <h2>Follow-Up Notes</h2>
        ${renderList(summary.followUpNotes)}
      </section>
    </main>`
  );
}

function renderSummaryHtml(result: ReviewResult): string {
  const { evidence, concerns, summary } = result;
  return htmlDocument(
    `${productName} Summary`,
    `<main class="shell compact">
      <section class="hero">
        <div class="hero-title">
          <span class="report-mark" aria-hidden="true">${productIconSvg}</span>
          <div>
            <p class="eyebrow">Review Summary</p>
            <h1>${escapeHtml(readableHost(evidence.input.websiteUrl))}</h1>
            <p>${escapeHtml(evidence.input.companyName ?? "Public website")}</p>
          </div>
        </div>
        <div class="score">
          <span>${escapeHtml(summary.riskLevel)}</span>
          <small>${concerns.length} concern${concerns.length === 1 ? "" : "s"}</small>
        </div>
      </section>
      <section>
        <h2>Visible Conclusion</h2>
        ${renderVisibleConclusionHtml(result)}
      </section>
      <section>
        <h2>Decision Brief</h2>
        ${renderDecisionBriefHtml(result)}
      </section>
      <section>
        <h2>Key Concerns</h2>
        ${
          concerns.length === 0
            ? `<p class="muted">No concerns were found by the built-in checks.</p>`
            : renderList(concerns.slice(0, 8).map((concern) => concern.message))
        }
      </section>
      <section>
        <h2>Final Assessment</h2>
        ${renderAssessmentHtml(result)}
      </section>
      <section>
        <h2>Site Identity Summary</h2>
        ${renderSiteIdentityHtml(result)}
      </section>
      <section>
        <h2>Domain And Page Dates</h2>
        ${renderDomainDatesHtml(result)}
      </section>
      <section>
        <h2>External Evidence</h2>
        ${renderExternalEvidenceHtml(result)}
      </section>
      <section>
        <h2>Category Assessment</h2>
        ${renderCategoryAssessmentHtml(result)}
      </section>
      <section>
        <h2>Priority Follow-Up</h2>
        ${renderPriorityHtml(result)}
      </section>
      <section>
        <h2>Suggested Next Steps</h2>
        ${renderChecklistHtml(result)}
      </section>
      <section class="metrics">
        ${renderSnapshotHtml(result)}
      </section>
      <section>
        <h2>Verification Coverage</h2>
        ${renderCoverageHtml(result)}
      </section>
      <section>
        <h2>Public Details Found</h2>
        ${renderSignalsHtml(result)}
      </section>
      <section>
        <h2>Reviewed Pages</h2>
        ${renderList(evidence.pages.map((page) => page.finalUrl))}
      </section>
    </main>`
  );
}

function htmlDocument(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <link rel="icon" href="${escapeAttribute(productIconDataUri)}">
  <style>
    :root {
      color-scheme: light;
      --ink: #161513;
      --muted: #69645f;
      --line: #ded8d1;
      --paper: #ffffff;
      --soft: #fbf9f7;
      --brand: #c74634;
      --brand-dark: #9f2d20;
      --blue: #2f6f9f;
      --green: #4f7d3f;
      --amber: #9a6b22;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: linear-gradient(180deg, #faf8f5 0%, #f5f2ef 52%, #eee9e3 100%);
      color: var(--ink);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.55;
    }
    a { color: var(--blue); }
    .shell {
      width: min(1120px, calc(100% - 32px));
      margin: 0 auto;
      padding: 32px 0 56px;
    }
    .compact { width: min(840px, calc(100% - 32px)); }
    .hero {
      display: flex;
      align-items: end;
      justify-content: space-between;
      gap: 24px;
      padding: 28px;
      background:
        linear-gradient(135deg, rgba(255, 255, 255, 0.96), rgba(251, 249, 247, 0.92)),
        linear-gradient(135deg, rgba(199, 70, 52, 0.12), rgba(47, 111, 159, 0.06));
      border: 1px solid var(--line);
      border-radius: 8px;
      box-shadow: 0 18px 45px rgba(31, 41, 51, 0.08);
    }
    .hero-title {
      display: flex;
      align-items: center;
      gap: 16px;
      min-width: 0;
    }
    .report-mark {
      width: 54px;
      height: 54px;
      flex: 0 0 auto;
      display: block;
      overflow: hidden;
      border-radius: 14px;
      box-shadow: 0 10px 22px rgba(199, 70, 52, 0.16);
    }
    .report-mark svg { width: 100%; height: 100%; display: block; }
    .eyebrow {
      margin: 0 0 6px;
      color: var(--brand-dark);
      font-size: 0.78rem;
      font-weight: 800;
      letter-spacing: 0;
      text-transform: uppercase;
    }
    h1, h2 { margin: 0; line-height: 1.1; }
    h1 { font-size: clamp(2rem, 5vw, 4.25rem); }
    h2 { font-size: 1.3rem; }
    .hero p:last-child { margin-bottom: 0; color: var(--muted); }
    .score {
      min-width: 220px;
      padding: 18px;
      border-left: 5px solid var(--brand);
      background: var(--soft);
      border-radius: 8px;
    }
    .score span { display: block; font-size: 1.35rem; font-weight: 800; }
    .score small { color: var(--muted); }
    section {
      margin-top: 22px;
      padding: 24px;
      background: var(--paper);
      border: 1px solid var(--line);
      border-radius: 8px;
    }
    .decision-card {
      display: grid;
      gap: 18px;
      padding: 20px;
      background: linear-gradient(135deg, #fff, var(--soft));
      border: 1px solid var(--line);
      border-left: 5px solid var(--brand);
      border-radius: 8px;
    }
    .decision-card h3 {
      margin: 0 0 8px;
      font-size: 1.35rem;
    }
    .decision-card h4 {
      margin: 0 0 8px;
      font-size: 0.92rem;
      color: var(--muted);
      text-transform: uppercase;
      letter-spacing: 0;
    }
    .decision-grid {
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 14px;
    }
    .decision-grid section {
      margin: 0;
      padding: 16px;
      background: #fff;
    }
    .metrics {
      display: grid;
      grid-template-columns: repeat(3, minmax(0, 1fr));
      gap: 14px;
      padding: 0;
      background: transparent;
      border: 0;
    }
    .metrics article {
      padding: 20px;
      background: var(--paper);
      border: 1px solid var(--line);
      border-radius: 8px;
    }
    .metrics strong { display: block; font-size: 2rem; }
    .metrics span, .muted { color: var(--muted); }
    .detail-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 14px;
    }
    .detail {
      padding: 16px;
      background: var(--soft);
      border: 1px solid var(--line);
      border-radius: 8px;
      overflow-wrap: anywhere;
    }
    .detail strong {
      display: block;
      margin-bottom: 8px;
    }
    ul { padding-left: 1.2rem; }
    .checklist {
      list-style: none;
      padding-left: 0;
    }
    .checklist li {
      display: flex;
      gap: 10px;
      align-items: flex-start;
    }
    .box {
      width: 1rem;
      height: 1rem;
      flex: 0 0 auto;
      margin-top: 0.25rem;
      border: 1px solid var(--line);
      border-radius: 4px;
      background: var(--soft);
    }
    li + li { margin-top: 8px; }
    .concern {
      padding: 16px;
      border: 1px solid var(--line);
      border-left: 5px solid var(--amber);
      border-radius: 8px;
    }
    .concern + .concern { margin-top: 12px; }
    .concern.high { border-left-color: var(--coral); }
    .concern.low { border-left-color: var(--green); }
    .concern strong { display: block; }
    .concern span { color: var(--muted); font-size: 0.92rem; }
    .category {
      margin-top: 16px;
    }
    .category h3 {
      margin: 0 0 10px;
      font-size: 1rem;
    }
    .table-wrap { overflow-x: auto; }
    table { width: 100%; border-collapse: collapse; min-width: 920px; }
    th, td { padding: 12px; border-bottom: 1px solid var(--line); text-align: left; vertical-align: top; }
    th { color: var(--muted); font-size: 0.82rem; text-transform: uppercase; letter-spacing: 0; }
    .gallery {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
      gap: 16px;
    }
    figure {
      margin: 0;
      border: 1px solid var(--line);
      border-radius: 8px;
      overflow: hidden;
      background: #f8fafc;
    }
    figure img {
      display: block;
      width: 100%;
      aspect-ratio: 16 / 10;
      object-fit: cover;
      object-position: top;
      border-bottom: 1px solid var(--line);
    }
    figcaption { padding: 10px 12px; color: var(--muted); font-size: 0.9rem; }
    figcaption strong, figcaption span { display: block; }
    @media (max-width: 760px) {
      .hero { align-items: stretch; flex-direction: column; }
      .score { min-width: 0; }
      .metrics { grid-template-columns: 1fr; }
      .decision-grid { grid-template-columns: 1fr; }
      section, .hero { padding: 18px; }
    }
  </style>
</head>
<body>
${body}
</body>
</html>`;
}

function renderAssessmentMarkdown(result: ReviewResult): string[] {
  const assessment = result.summary.finalAssessment;
  return [
    `- Assessment: ${assessment.label}`,
    `- Recommendation: ${assessment.recommendation}`,
    "- Reasons:",
    ...assessment.reasons.map((reason) => `  - ${reason}`)
  ];
}

function renderVisibleConclusionMarkdown(result: ReviewResult): string[] {
  return [
    `- Review outcome: ${result.summary.riskLevel}`,
    `- Confidence: ${result.summary.confidence}`,
    `- Likely official website: ${result.summary.likelyOfficialWebsite}`,
    "- Caution: this report is based on reviewed public website pages and public domain-date data available during this run. Unknown items are labeled for manual follow-up rather than treated as negative findings."
  ];
}

function renderVisibleConclusionPlain(result: ReviewResult): string[] {
  return [
    `- Review outcome: ${result.summary.riskLevel}`,
    `- Confidence: ${result.summary.confidence}`,
    `- Likely official website: ${result.summary.likelyOfficialWebsite}`
  ];
}

function renderVisibleConclusionHtml(result: ReviewResult): string {
  return `<div class="detail-grid">
    <article class="detail">
      <strong>Review Outcome</strong>
      <p>${escapeHtml(result.summary.riskLevel)}</p>
    </article>
    <article class="detail">
      <strong>Confidence</strong>
      <p>${escapeHtml(result.summary.confidence)}</p>
    </article>
    <article class="detail">
      <strong>Likely Official Website</strong>
      <p>${escapeHtml(result.summary.likelyOfficialWebsite)}</p>
    </article>
    <article class="detail">
      <strong>Scope Note</strong>
      <p>This report is based on reviewed public website pages and public domain-date data available during this run. Unknown items are labeled for manual follow-up rather than treated as negative findings.</p>
    </article>
  </div>`;
}

function renderDecisionBriefMarkdown(result: ReviewResult): string[] {
  const brief = result.summary.decisionBrief;
  return [
    `- Headline: ${brief.headline}`,
    `- Recommendation: ${brief.recommendation}`,
    "- Top findings:",
    ...brief.topFindings.map((item) => `  - ${item}`),
    "- Next steps:",
    ...brief.nextSteps.map((item) => `  - ${item}`)
  ];
}

function renderDecisionBriefHtml(result: ReviewResult): string {
  const brief = result.summary.decisionBrief;
  return `<article class="decision-card">
    <div>
      <p class="eyebrow">Decision-ready summary</p>
      <h3>${escapeHtml(brief.headline)}</h3>
      <p>${escapeHtml(brief.recommendation)}</p>
    </div>
    <div class="decision-grid">
      <section>
        <h4>Top Findings</h4>
        ${renderList(brief.topFindings)}
      </section>
      <section>
        <h4>Next Steps</h4>
        ${renderList(brief.nextSteps)}
      </section>
    </div>
  </article>`;
}

function renderAssessmentPlain(result: ReviewResult): string[] {
  const assessment = result.summary.finalAssessment;
  return [
    `- Assessment: ${assessment.label}`,
    `- Recommendation: ${assessment.recommendation}`,
    ...assessment.reasons.map((reason) => `- Reason: ${reason}`)
  ];
}

function renderAssessmentHtml(result: ReviewResult): string {
  const assessment = result.summary.finalAssessment;
  return `<article class="detail">
    <strong>${escapeHtml(assessment.label)}</strong>
    ${renderList(assessment.reasons)}
    <p>${escapeHtml(assessment.recommendation)}</p>
  </article>`;
}

function renderSiteIdentityMarkdown(result: ReviewResult): string[] {
  const identity = result.evidence.siteIdentity;
  if (!identity) {
    return ["- Site identity summary was not available for this review."];
  }

  return [
    `- Likely official website: ${identity.likelyOfficialSite}`,
    `- Entity match: ${identity.matchLevel}`,
    `- Reviewed domain: ${identity.reviewedDomain || "not available"}`,
    `- Provided details: ${formatProvided(identity)}`,
    `- Found on reviewed pages: company name ${providedDetailStatus(identity.provided.companyName, identity.found.companyNameInText)}, location ${providedDetailStatus(
      identity.provided.claimedLocation,
      identity.found.claimedLocationInText
    )}, industry/service ${providedDetailStatus(identity.provided.claimedIndustry, identity.found.claimedIndustryInText)}, ${identity.found.emailDomains.length} email domain${identity.found.emailDomains.length === 1 ? "" : "s"}, ${
      identity.found.phones.length
    } phone number${identity.found.phones.length === 1 ? "" : "s"}, ${identity.found.addressLines.length} address-like line${
      identity.found.addressLines.length === 1 ? "" : "s"
    }, ${identity.found.socialLinks.length} social link${identity.found.socialLinks.length === 1 ? "" : "s"}`,
    `- Email domains: ${identity.found.emailDomains.length ? identity.found.emailDomains.join(", ") : "none found"}`,
    `- Copyright-style names: ${identity.found.copyrightNames.length ? identity.found.copyrightNames.join(", ") : "none found"}`,
    `- Related domains: ${formatRelatedDomains(identity)}`,
    `- Common entry points: ${formatEntryPointsMarkdown(result.evidence.siteAvailability)}`,
    "- Source note: provided details came from the user, found details came from reviewed website pages, and manual follow-up items are not independently confirmed by this app.",
    "",
    "### Identity Reasons",
    "",
    ...bulletList(identity.reasons),
    "",
    "### Manual Follow-Up Recommended",
    "",
    ...bulletList(identity.manualFollowUps)
  ];
}

function renderSiteIdentityPlain(result: ReviewResult): string[] {
  const identity = result.evidence.siteIdentity;
  if (!identity) {
    return ["- Site identity summary was not available for this review."];
  }

  return [
    `- Likely official website: ${identity.likelyOfficialSite}`,
    `- Entity match: ${identity.matchLevel}`,
    `- Reviewed domain: ${identity.reviewedDomain || "not available"}`,
    `- Key reasons: ${identity.reasons.slice(0, 3).join(" ")}`,
    `- Manual follow-up: ${identity.manualFollowUps.slice(0, 3).join(" ")}`
  ];
}

function renderSiteIdentityHtml(result: ReviewResult): string {
  const identity = result.evidence.siteIdentity;
  if (!identity) {
    return `<p class="muted">Site identity summary was not available for this review.</p>`;
  }

  return `<div class="detail-grid">
    <article class="detail">
      <strong>Likely Official Website</strong>
      <p>${escapeHtml(identity.likelyOfficialSite)}</p>
      <p class="muted">Entity match: ${escapeHtml(identity.matchLevel)}</p>
    </article>
    <article class="detail">
      <strong>Provided By User</strong>
      <ul>
        <li>Company: ${escapeHtml(identity.provided.companyName ?? "not provided")}</li>
        <li>Location: ${escapeHtml(identity.provided.claimedLocation ?? "not provided")}</li>
        <li>Expected state: ${escapeHtml(identity.provided.expectedState ?? "not provided")}</li>
        <li>Industry/service: ${escapeHtml(identity.provided.claimedIndustry ?? "not provided")}</li>
        <li>Additional identifiers: ${escapeHtml(identity.provided.additionalIdentifiers ?? "not provided")}</li>
      </ul>
    </article>
    <article class="detail">
      <strong>Found On Reviewed Pages</strong>
      <ul>
        <li>Company name: ${providedDetailHtmlStatus(identity.provided.companyName, identity.found.companyNameInText)}</li>
        <li>Location: ${providedDetailHtmlStatus(identity.provided.claimedLocation, identity.found.claimedLocationInText)}</li>
        <li>Industry/service: ${providedDetailHtmlStatus(identity.provided.claimedIndustry, identity.found.claimedIndustryInText)}</li>
        <li>Email domains: ${escapeHtml(identity.found.emailDomains.length ? identity.found.emailDomains.join(", ") : "none found")}</li>
        <li>Phones: ${identity.found.phones.length}</li>
        <li>Address-like lines: ${identity.found.addressLines.length}</li>
        <li>Social links: ${identity.found.socialLinks.length}</li>
      </ul>
    </article>
    <article class="detail">
      <strong>Common Entry Points</strong>
      ${renderEntryPointsHtml(result.evidence.siteAvailability)}
    </article>
    <article class="detail">
      <strong>Related Domains</strong>
      ${renderRelatedDomainsHtml(identity)}
    </article>
    <article class="detail">
      <strong>Source Note</strong>
      <p>Provided details came from the user. Found details came from reviewed website pages. Manual follow-up items are not independently confirmed by this app.</p>
    </article>
    <article class="detail">
      <strong>Identity Reasons</strong>
      ${renderList(identity.reasons)}
    </article>
    <article class="detail">
      <strong>Manual Follow-Up Recommended</strong>
      ${renderList(identity.manualFollowUps)}
    </article>
  </div>`;
}

function formatProvided(identity: SiteIdentityReview): string {
  const values = [
    identity.provided.companyName ? `company "${identity.provided.companyName}"` : "company not provided",
    identity.provided.claimedLocation ? `location "${identity.provided.claimedLocation}"` : "location not provided",
    identity.provided.expectedState ? `expected state "${identity.provided.expectedState}"` : "expected state not provided",
    identity.provided.claimedIndustry ? `industry/service "${identity.provided.claimedIndustry}"` : "industry/service not provided",
    identity.provided.additionalIdentifiers ? `additional identifiers "${identity.provided.additionalIdentifiers}"` : "additional identifiers not provided"
  ];
  return values.join(", ");
}

function renderDomainDatesMarkdown(result: ReviewResult): string[] {
  const registration = result.evidence.domainRegistration;
  return [
    `- Domain checked: ${registration?.domain || readableHost(result.evidence.input.websiteUrl)}`,
    `- Registration lookup status: ${formatDomainRegistrationStatus(result)}`,
    `- Domain creation date: ${registration?.creationDate ?? "not available"}`,
    `- Domain last changed date: ${registration?.lastChangedDate ?? "not available"}`,
    `- Domain expiration date: ${registration?.expirationDate ?? "not available"}`,
    `- Registrar: ${registration?.registrar ?? "not available"}`,
    `- Name servers: ${registration?.nameServers.length ? registration.nameServers.join(", ") : "not available"}`,
    `- Homepage last modified: ${formatHomepageLastModified(result)}`,
    "- Source note: domain dates come from public registration data when available. The business registration item remains a manual follow-up."
  ];
}

function renderDomainDatesPlain(result: ReviewResult): string[] {
  const registration = result.evidence.domainRegistration;
  return [
    `- Domain checked: ${registration?.domain || readableHost(result.evidence.input.websiteUrl)}`,
    `- Domain creation date: ${registration?.creationDate ?? "not available"}`,
    `- Domain last changed date: ${registration?.lastChangedDate ?? "not available"}`,
    `- Homepage last modified: ${formatHomepageLastModified(result)}`,
    result.evidence.input.expectedState
      ? `- Manual business registration follow-up state: ${result.evidence.input.expectedState}`
      : "- Manual business registration follow-up state: not provided"
  ];
}

function renderDomainDatesHtml(result: ReviewResult): string {
  const registration = result.evidence.domainRegistration;
  const items = [
    ["Domain checked", registration?.domain || readableHost(result.evidence.input.websiteUrl)],
    ["Registration lookup", formatDomainRegistrationStatus(result)],
    ["Creation date", registration?.creationDate ?? "not available"],
    ["Last changed date", registration?.lastChangedDate ?? "not available"],
    ["Expiration date", registration?.expirationDate ?? "not available"],
    ["Registrar", registration?.registrar ?? "not available"],
    ["Name servers", registration?.nameServers.length ? registration.nameServers.join(", ") : "not available"],
    ["Homepage last modified", formatHomepageLastModified(result)],
    ["Manual registration follow-up state", result.evidence.input.expectedState ?? "not provided"]
  ];

  return `<div class="detail-grid">${items
    .map(
      ([label, value]) => `<article class="detail">
        <strong>${escapeHtml(label)}</strong>
        <p>${escapeHtml(value)}</p>
      </article>`
    )
    .join("")}</div>`;
}

function formatDomainRegistrationStatus(result: ReviewResult): string {
  const registration = result.evidence.domainRegistration;
  if (!registration) {
    return "not checked";
  }
  if (registration.status === "found") {
    return "found";
  }
  return registration.note ? `${registration.status}; ${registration.note}` : registration.status.replace(/_/g, " ");
}

function formatHomepageLastModified(result: ReviewResult): string {
  const lastModified = result.evidence.pages[0]?.lastModified;
  if (!lastModified) {
    return "not available";
  }
  return formatPageLastModified(lastModified);
}

function formatPageLastModified(lastModified: PageLastModifiedEvidence): string {
  return `${lastModified.value} (${lastModified.source === "http_header" ? "HTTP header" : "page metadata"})`;
}

function renderExternalEvidenceMarkdown(result: ReviewResult): string[] {
  const external = result.evidence.externalEvidence;
  if (!external) {
    return ["- External evidence was not generated for this review."];
  }

  const lines = [
    `- Checked at: ${external.checkedAt}`,
    "- Label key: verified from reviewed website means the item was found on pages this app reviewed; found in public external source means a public source was queried successfully; manual follow-up recommended means the app generated a source link but did not interpret the result; could not verify from local run means the check was unavailable or incomplete.",
    "",
    "### Evidence Items",
    "",
    ...external.items.map((item) => `- ${item.title}: ${item.label}. ${item.detail}${item.sourceUrl ? ` Source: ${item.sourceName} (${item.sourceUrl})` : ` Source: ${item.sourceName}.`}`),
    "",
    "### State Registry Checklist",
    "",
    ...(external.registryChecks.length
      ? external.registryChecks.flatMap((registry) => [
          `- ${registry.state}: ${registry.label}. Search "${registry.suggestedSearch}" in ${registry.agency}.`,
          `  - Search URL: ${registry.searchUrl}`,
          `  - Source URL: ${registry.sourceUrl}`,
          ...registry.notes.map((note) => `  - Note: ${note}`)
        ])
      : ["- No supported state registry checklist was generated. Provide an expected state to generate one."]),
    "",
    "### Public Search Links",
    "",
    ...(external.searchLinks.length
      ? external.searchLinks.map((link) => `- ${link.label}: ${link.confidenceLabel}. Query: ${link.query}. URL: ${link.url}`)
      : ["- No public search links were generated."]),
    "",
    "### Website-Discovered Profile Links",
    "",
    ...(external.profileLinks.length
      ? external.profileLinks.map((profile) => `- ${profile.platform}: ${profile.label}. ${profile.url}. Source page: ${profile.sourcePageUrl}. ${profile.detail}`)
      : ["- No external profile links were found on reviewed website pages."])
  ];

  return lines;
}

function renderExternalEvidencePlain(result: ReviewResult): string[] {
  const external = result.evidence.externalEvidence;
  if (!external) {
    return ["- External evidence was not generated for this review."];
  }

  return [
    `- Checked at: ${external.checkedAt}`,
    ...external.items.slice(0, 6).map((item) => `- ${item.title}: ${item.label}. ${item.detail}`),
    ...external.registryChecks.slice(0, 3).map((registry) => `- Registry follow-up: search ${registry.agency} for "${registry.suggestedSearch}" at ${registry.searchUrl}`),
    external.searchLinks.length ? `- Public search links generated: ${external.searchLinks.length}` : "- Public search links generated: 0",
    external.profileLinks.length ? `- Website-discovered profile links: ${external.profileLinks.length}` : "- Website-discovered profile links: 0"
  ];
}

function renderExternalEvidenceHtml(result: ReviewResult): string {
  const external = result.evidence.externalEvidence;
  if (!external) {
    return `<p class="muted">External evidence was not generated for this review.</p>`;
  }

  return `<div class="detail-grid">
    <article class="detail">
      <strong>Evidence Labels</strong>
      <ul>
        <li>Verified from reviewed website</li>
        <li>Found in public external source</li>
        <li>Manual follow-up recommended</li>
        <li>Could not verify from local run</li>
      </ul>
    </article>
    <article class="detail">
      <strong>Evidence Items</strong>
      ${renderExternalEvidenceItemList(external)}
    </article>
    <article class="detail">
      <strong>State Registry Checklist</strong>
      ${renderRegistryChecklistHtml(external)}
    </article>
    <article class="detail">
      <strong>Public Search Links</strong>
      ${renderExternalSearchLinksHtml(external)}
    </article>
    <article class="detail">
      <strong>Website-Discovered Profile Links</strong>
      ${renderExternalProfileLinksHtml(external)}
    </article>
  </div>`;
}

function renderExternalEvidenceItemList(external: ExternalEvidence): string {
  if (external.items.length === 0) {
    return `<p class="muted">No external evidence items were generated.</p>`;
  }

  return `<ul>${external.items
    .slice(0, 10)
    .map(
      (item) =>
        `<li><strong>${escapeHtml(item.title)}</strong>: ${escapeHtml(item.label)}. ${escapeHtml(item.detail)} ${
          item.sourceUrl ? `<a href="${escapeAttribute(item.sourceUrl)}">${escapeHtml(item.sourceName)}</a>` : escapeHtml(item.sourceName)
        }</li>`
    )
    .join("")}</ul>`;
}

function renderRegistryChecklistHtml(external: ExternalEvidence): string {
  if (external.registryChecks.length === 0) {
    return `<p class="muted">No supported state registry checklist was generated. Provide an expected state to generate one.</p>`;
  }

  return `<ul>${external.registryChecks
    .map(
      (registry) => `<li>
        <strong>${escapeHtml(registry.state)}</strong>: search "${escapeHtml(registry.suggestedSearch)}" in
        <a href="${escapeAttribute(registry.searchUrl)}">${escapeHtml(registry.agency)}</a>.
        <span class="muted">${escapeHtml(registry.notes.join(" "))}</span>
      </li>`
    )
    .join("")}</ul>`;
}

function renderExternalSearchLinksHtml(external: ExternalEvidence): string {
  if (external.searchLinks.length === 0) {
    return `<p class="muted">No public search links were generated.</p>`;
  }

  return `<ul>${external.searchLinks
    .map((link) => `<li><a href="${escapeAttribute(link.url)}">${escapeHtml(link.label)}</a><br><span class="muted">${escapeHtml(link.query)}</span></li>`)
    .join("")}</ul>`;
}

function renderExternalProfileLinksHtml(external: ExternalEvidence): string {
  if (external.profileLinks.length === 0) {
    return `<p class="muted">No external profile links were found on reviewed pages.</p>`;
  }

  return `<ul>${external.profileLinks
    .slice(0, 12)
    .map(
      (profile) => `<li><a href="${escapeAttribute(profile.url)}">${escapeHtml(profile.platform)}</a>: ${escapeHtml(profile.label)}${
        profile.status ? `, HTTP ${profile.status}` : ""
      }<br><span class="muted">Source page: ${escapeHtml(profile.sourcePageUrl)}</span></li>`
    )
    .join("")}</ul>`;
}

function renderCategoryAssessmentMarkdown(result: ReviewResult): string[] {
  if (result.summary.categoryAssessments.length === 0) {
    return ["- Category assessment was not available for this review."];
  }

  const lines: string[] = [];
  for (const category of result.summary.categoryAssessments) {
    lines.push(`### ${category.label}`, "");
    lines.push(`- Level: ${category.level}`);
    if (category.evidence.length) {
      lines.push("- Evidence:");
      lines.push(...category.evidence.map((item) => `  - ${item}`));
    }
    if (category.unknowns.length) {
      lines.push("- Unknown or unverified:");
      lines.push(...category.unknowns.map((item) => `  - ${item}`));
    }
    if (category.manualFollowUps.length) {
      lines.push("- Manual follow-up recommended:");
      lines.push(...category.manualFollowUps.map((item) => `  - ${item}`));
    }
    lines.push("");
  }

  return lines;
}

function renderCategoryAssessmentPlain(result: ReviewResult): string[] {
  return result.summary.categoryAssessments.flatMap((category) => [
    `- ${category.label}: ${category.level}`,
    ...category.unknowns.map((item) => `- Manual follow-up: ${item}`)
  ]);
}

function renderCategoryAssessmentHtml(result: ReviewResult): string {
  if (result.summary.categoryAssessments.length === 0) {
    return `<p class="muted">Category assessment was not available for this review.</p>`;
  }

  return `<div class="detail-grid">${result.summary.categoryAssessments
    .map(
      (category) => `<article class="detail">
        <strong>${escapeHtml(category.label)}</strong>
        <p>${escapeHtml(category.level)}</p>
        ${category.evidence.length ? renderList(category.evidence) : ""}
        ${category.unknowns.length ? `<p class="muted">Unknown or unverified</p>${renderList(category.unknowns)}` : ""}
        ${category.manualFollowUps.length ? `<p class="muted">Manual follow-up recommended</p>${renderList(category.manualFollowUps)}` : ""}
      </article>`
    )
    .join("")}</div>`;
}

function formatRelatedDomains(identity: SiteIdentityReview): string {
  if (identity.relatedDomains.length === 0) {
    return "none found";
  }
  return identity.relatedDomains
    .slice(0, 10)
    .map((item) => `${item.domain} (${item.sources.join(", ")})`)
    .join(" | ");
}

function renderRelatedDomainsHtml(identity: SiteIdentityReview): string {
  if (identity.relatedDomains.length === 0) {
    return `<p class="muted">None found</p>`;
  }
  return `<ul>${identity.relatedDomains
    .slice(0, 10)
    .map((item) => `<li>${escapeHtml(item.domain)} <span class="muted">(${escapeHtml(item.sources.join(", "))})</span></li>`)
    .join("")}</ul>`;
}

function formatEntryPointsMarkdown(checks: UrlVariantCheck[] | undefined): string {
  if (!checks?.length) {
    return "not available";
  }
  return checks.map(formatEntryPoint).join(" | ");
}

function renderEntryPointsHtml(checks: UrlVariantCheck[] | undefined): string {
  if (!checks?.length) {
    return `<p class="muted">Not available</p>`;
  }
  return `<ul>${checks.map((check) => `<li>${escapeHtml(formatEntryPoint(check))}</li>`).join("")}</ul>`;
}

function formatEntryPoint(check: UrlVariantCheck): string {
  const status = check.status ? `HTTP ${check.status}` : check.note ? "not loaded" : "not available";
  const outcome = check.ok ? "Loaded" : "Needs follow-up";
  const finalUrl = check.finalUrl && check.finalUrl !== check.url ? ` -> ${check.finalUrl}` : "";
  return `${check.url}: ${outcome} (${status})${finalUrl}`;
}

function providedDetailStatus(value: string | undefined, found: boolean): string {
  if (!value) {
    return "not provided";
  }
  return found ? "found" : "not found";
}

function providedDetailHtmlStatus(value: string | undefined, found: boolean): string {
  if (!value) {
    return "Not provided";
  }
  return found ? "Found" : "Needs follow-up";
}

function renderGroupedConcerns(concerns: ReviewConcern[]): string {
  if (concerns.length === 0) {
    return `<p class="muted">No concerns were found by the built-in checks.</p>`;
  }

  return groupConcerns(concerns)
    .map(
      ([area, groupedConcerns]) => `<div class="category">
        <h3>${escapeHtml(areaLabel(area))}</h3>
        ${groupedConcerns.map((concern) => renderConcern(concern)).join("\n")}
      </div>`
    )
    .join("\n");
}

function renderConcern(concern: ReviewConcern): string {
  return `<article class="concern ${escapeAttribute(concern.severity)}">
    <strong>${escapeHtml(concern.label ? `${concern.label}: ${concern.message}` : concern.message)}</strong>
    <span>${escapeHtml(concern.severity)}</span>
    ${concern.pageUrl ? `<p><a href="${escapeAttribute(concern.pageUrl)}">${escapeHtml(concern.pageUrl)}</a></p>` : ""}
    ${concern.evidence ? `<p class="muted">${escapeHtml(concern.evidence)}</p>` : ""}
  </article>`;
}

export function renderPlainSummary(result: ReviewResult): string {
  const { evidence, summary } = result;
  const lines = [
    `${productName} Summary`,
    "",
    `Website: ${evidence.input.websiteUrl}`,
    evidence.input.companyName ? `Company: ${evidence.input.companyName}` : undefined,
    evidence.input.claimedLocation ? `Location: ${evidence.input.claimedLocation}` : undefined,
    evidence.input.expectedState ? `Expected state: ${evidence.input.expectedState}` : undefined,
    evidence.input.claimedIndustry ? `Industry/service: ${evidence.input.claimedIndustry}` : undefined,
    evidence.input.additionalIdentifiers ? `Additional identifiers: ${evidence.input.additionalIdentifiers}` : undefined,
    `Review outcome: ${summary.riskLevel}`,
    `Concern level: ${summary.concernLevel}`,
    `Confidence: ${summary.confidence}`,
    `Likely official website: ${summary.likelyOfficialWebsite}`,
    "",
    "Visible Conclusion:",
    ...renderVisibleConclusionPlain(result),
    "",
    "Verified Facts:",
    ...summary.verifiedFacts.map((line) => `- ${line}`),
    "",
    "Positive Indicators:",
    ...summary.positiveIndicators.map((line) => `- ${line}`),
    "",
    "Unknown Or Unverified:",
    ...(summary.unknowns.length ? summary.unknowns : ["No unknown items were generated by the built-in checks."]).map((line) => `- ${line}`),
    "",
    "Review Snapshot:",
    ...renderSnapshotMarkdown(result).map((line) => line.replace(/^- /, "- ")),
    "",
    "Summary:",
    ...executiveSummary(result).map((line) => `- ${line}`),
    "",
    "Decision Brief:",
    `- ${result.summary.decisionBrief.headline}`,
    `- Recommendation: ${result.summary.decisionBrief.recommendation}`,
    ...result.summary.decisionBrief.topFindings.map((line) => `- Finding: ${line}`),
    "",
    "Final Assessment:",
    ...renderAssessmentPlain(result),
    "",
    "Site Identity:",
    ...renderSiteIdentityPlain(result),
    "",
    "Domain And Page Dates:",
    ...renderDomainDatesPlain(result),
    "",
    "External Evidence:",
    ...renderExternalEvidencePlain(result),
    "",
    "Category Assessment:",
    ...renderCategoryAssessmentPlain(result),
    "",
    "Priority Follow-Up:",
    ...renderPriorityPlain(result),
    "",
    "Suggested Next Steps:",
    ...renderChecklistItems(result).map((item) => `- ${item}`),
    "",
    completedOutputDir(result) ? `Report folder: ${completedOutputDir(result)}` : undefined
  ].filter((line): line is string => line !== undefined);

  return `${lines.join("\n")}\n`;
}

function completedOutputDir(result: ReviewResult): string {
  const withPaths = result as ReviewResult & { paths?: { outputDir?: string } };
  return withPaths.paths?.outputDir ?? "";
}

function renderChecklistMarkdown(result: ReviewResult): string {
  return [
    "# Follow-Up Checklist",
    "",
    `Website: ${result.evidence.input.websiteUrl}`,
    `Concern level: ${result.summary.concernLevel}`,
    "",
    ...renderChecklistItems(result).map((item) => `- [ ] ${item}`),
    ""
  ].join("\n");
}

function renderChecklistHtml(result: ReviewResult): string {
  const items = renderChecklistItems(result);
  if (items.length === 0) {
    return `<p class="muted">No follow-up items were generated by the built-in checks.</p>`;
  }

  return `<ul class="checklist">${items.map((item) => `<li><span class="box"></span><span>${escapeHtml(item)}</span></li>`).join("")}</ul>`;
}

function renderChecklistItems(result: ReviewResult): string[] {
  const items = [
    ...(result.summary.manualFollowUps ?? []),
    ...(result.evidence.siteIdentity?.manualFollowUps ?? []),
    ...externalEvidenceChecklistItems(result),
    ...result.concerns.map((concern) => actionForConcern(concern))
  ];
  const uniqueItems = [...new Set(items)];

  if (uniqueItems.length === 0) {
    return ["Review the report and screenshots for any business-specific details you want to confirm manually."];
  }

  return uniqueItems.slice(0, 12);
}

function externalEvidenceChecklistItems(result: ReviewResult): string[] {
  const external = result.evidence.externalEvidence;
  if (!external) {
    return [];
  }

  return uniqueStrings([
    ...external.registryChecks.map(
      (registry) => `Search ${registry.agency} for "${registry.suggestedSearch}" and compare the official record to the website details.`
    ),
    external.searchLinks.length
      ? "Open the generated public search links for reviews, complaints, map listings, directory references, and company profile signals."
      : undefined
  ]);
}

function actionForConcern(concern: ReviewConcern): string {
  if (concern.code === "broken_link") {
    return `Update or remove the broken link shown in the evidence: ${concern.evidence ?? concern.pageUrl ?? "see report"}.`;
  }
  if (concern.code.startsWith("missing_") && concern.code.endsWith("_page")) {
    return `Add or clearly link the expected page noted in the report: ${concern.message}`;
  }
  if (concern.code.startsWith("placeholder_")) {
    if (concern.code === "placeholder_zero_metrics") {
      return "Replace zeroed metric counters with real values or remove the counters until they can be supported.";
    }
    return `Replace placeholder wording on ${concern.pageUrl ?? "the listed page"}.`;
  }
  if (concern.code === "common_misspelling") {
    return `Review and correct the possible misspelling shown in the evidence: ${concern.evidence ?? "see report"}.`;
  }
  if (concern.code === "thin_visible_text") {
    return `Review whether ${concern.pageUrl ?? "the listed page"} needs more useful visible content.`;
  }
  if (concern.code === "weak_page_title" || concern.code === "duplicate_page_title") {
    return "Review page titles so important pages have clear, distinct names.";
  }
  if (concern.code === "page_limit_reached") {
    return "Run another review with a higher page limit if you need broader site coverage.";
  }
  if (concern.code.startsWith("social_link_") || concern.code === "social_label_without_profile_link") {
    return `Review the social link destination shown in the evidence: ${concern.evidence ?? concern.pageUrl ?? "see report"}.`;
  }
  if (concern.code === "template_like_writing" || concern.code === "repeated_sentence_starts" || concern.code === "repeated_content_blocks") {
    return "Review the listed writing patterns and replace generic wording with specific business details.";
  }
  if (concern.code === "stale_job_or_deadline_date") {
    return "Update or remove stale job, application, or deadline dates shown in the evidence.";
  }
  if (concern.code === "dummy_or_irrelevant_commerce_content") {
    return "Remove unrelated sample product or cart content unless the business intentionally sells those products.";
  }
  if (concern.code === "third_party_service_reference") {
    return "Review the outside provider or domain reference and confirm whether the page content is original and authorized.";
  }
  if (concern.code === "unsupported_marketing_claims") {
    return "Add supporting details for broad marketing claims, or replace them with more specific and verifiable wording.";
  }
  if (concern.code === "multiple_content_authenticity_markers") {
    return "Review the combined content-quality markers before treating the site as polished or ready for customer-facing use.";
  }
  if (concern.code === "generic_wording_heavy") {
    return "Replace repeated generic marketing phrases with specific services, locations, credentials, or examples.";
  }
  if (
    concern.code === "contact_email_common_provider" ||
    concern.code === "contact_email_domain_mismatch" ||
    concern.code === "contact_email_lookalike_domain" ||
    concern.code === "only_hr_contact_email"
  ) {
    return "Review whether the listed contact email should use the business website domain.";
  }
  if (concern.code === "different_business_name_seen" || concern.code === "multiple_business_names_seen") {
    return "Confirm whether the listed business name belongs to the same organization.";
  }
  if (concern.code === "multiple_contact_email_domains") {
    return "Confirm which email domain should be used for official business contact.";
  }
  if (concern.code === "multiple_contact_phones") {
    return "Confirm which phone number should be used for official business contact.";
  }
  if (concern.code === "multiple_address_lines") {
    return "Confirm whether the listed address-like lines are current business locations.";
  }
  if (concern.code === "phone_area_code_location_mismatch") {
    return "Confirm whether the listed phone number is expected for the business location, especially if it is a mobile or VoIP number.";
  }
  if (concern.code === "multiple_business_identity_followups") {
    return "Resolve the combined business-detail follow-up items before relying on the website identity.";
  }
  if (concern.code === "contact_page_no_contact_method") {
    return "Add or confirm a clear email, phone number, or contact form on the contact page.";
  }
  if (concern.code === "email_not_seen") {
    return "Add a visible contact email or a clear contact form path.";
  }
  if (concern.code === "phone_not_seen") {
    return "Add a visible phone number if phone contact is expected for this business.";
  }
  if (concern.code === "company_name_not_seen") {
    return "Make sure the provided company name appears clearly on the reviewed pages.";
  }
  if (concern.code === "expected_state_not_seen") {
    return "Confirm whether the expected state should appear on the website or only in outside business records.";
  }
  if (concern.code === "claimed_industry_not_seen") {
    return "Confirm whether the provided industry or service matches what the website describes.";
  }
  if (concern.code === "regulated_industry_manual_follow_up") {
    return "Check licensing or professional registration if the provided industry requires it.";
  }
  if (concern.code === "provided_identifier_not_seen") {
    return "Compare the provided identifier against the website and trusted outside records.";
  }
  if (concern.code === "domain_date_after_business_history") {
    return "Compare the public domain creation date with the business-history wording shown on the website.";
  }
  if (concern.code === "payment_wording_manual_review") {
    return "Review the payment wording shown in the evidence before sending funds or documents.";
  }
  if (concern.code === "claimed_location_not_seen" || concern.code === "street_address_not_seen") {
    return "Make sure the provided location is shown clearly if location is important for the business.";
  }

  return `${concern.label ?? "Review"}: ${concern.message}`;
}

function executiveSummary(result: ReviewResult): string[] {
  const { evidence, concerns, summary } = result;
  const details = evidence.signals;
  const identity = evidence.siteIdentity;
  const commonPages = details ? Object.values(details.pagePresence).filter(Boolean).length : 0;
  const emailsFound = details?.emails?.length ?? 0;
  const phonesFound = details?.phones?.length ?? 0;
  const lines = [
    `${summary.riskLevel} with ${summary.confidence.toLowerCase()} confidence based on ${evidence.pages.length} reviewed page${
      evidence.pages.length === 1 ? "" : "s"
    }.`,
    `Likely official website: ${summary.likelyOfficialWebsite}.`,
    `Final assessment: ${summary.finalAssessment.label}.`,
    `${concerns.length} item${concerns.length === 1 ? "" : "s"} need follow-up from the built-in checks.`,
    `${emailsFound} email address${emailsFound === 1 ? "" : "es"}, ${
      phonesFound
    } phone number${phonesFound === 1 ? "" : "s"}, and ${commonPages} common page${
      commonPages === 1 ? "" : "s"
    } were found.`
  ];

  if (identity) {
    lines.push(`Site identity match: ${identity.matchLevel}. Likely official website: ${identity.likelyOfficialSite}.`);
  }

  return lines;
}

function renderPriorityMarkdown(result: ReviewResult): string[] {
  const concerns = priorityConcerns(result);
  if (concerns.length === 0) {
    return ["- No priority follow-up items were generated by the built-in checks."];
  }

  return concerns.map((concern) => `- ${formatConcern(concern)}`);
}

function renderPriorityPlain(result: ReviewResult): string[] {
  const concerns = priorityConcerns(result);
  if (concerns.length === 0) {
    return ["- No priority follow-up items were generated by the built-in checks."];
  }

  return concerns.map((concern) => `- ${concern.label ? `${concern.label}: ` : ""}${concern.message}`);
}

function renderPriorityHtml(result: ReviewResult): string {
  const concerns = priorityConcerns(result);
  if (concerns.length === 0) {
    return `<p class="muted">No priority follow-up items were generated by the built-in checks.</p>`;
  }

  return `<div class="concern-list">${concerns.map((concern) => renderConcern(concern)).join("\n")}</div>`;
}

function priorityConcerns(result: ReviewResult): ReviewConcern[] {
  const seen = new Set<string>();
  return result.concerns
    .filter((concern) => {
      const key = `${concern.code}|${concern.evidence ?? ""}|${concern.message}`;
      if (seen.has(key)) {
        return false;
      }
      seen.add(key);
      return true;
    })
    .sort((left, right) => severityRank(right.severity) - severityRank(left.severity))
    .slice(0, 5);
}

function renderSnapshotMarkdown(result: ReviewResult): string[] {
  const snapshot = result.summary.snapshot;
  return [
    `- Pages reviewed: ${snapshot.pagesReviewed}`,
    `- Concerns found: ${snapshot.concernsFound}`,
    `- Contact emails found: ${snapshot.emailsFound}`,
    `- Contact phones found: ${snapshot.phonesFound}`,
    `- Contact forms found: ${snapshot.contactFormsFound}`,
    `- Common pages found: ${snapshot.commonPagesFound}`,
    `- Screenshots captured: ${snapshot.screenshotsCaptured}`,
    `- Links recorded: ${snapshot.linksRecorded}`
  ];
}

function renderSnapshotHtml(result: ReviewResult): string {
  const snapshot = result.summary.snapshot;
  return [
    ["Pages reviewed", snapshot.pagesReviewed],
    ["Concerns", snapshot.concernsFound],
    ["Emails", snapshot.emailsFound],
    ["Phones", snapshot.phonesFound],
    ["Contact forms", snapshot.contactFormsFound],
    ["Common pages", snapshot.commonPagesFound],
    ["Screenshots", snapshot.screenshotsCaptured]
  ]
    .map(([label, value]) => `<article><strong>${value}</strong><span>${label}</span></article>`)
    .join("");
}

function renderCoverageMarkdown(result: ReviewResult): string[] {
  return coverageItems(result).map((item) => {
    const detail = item.detail ? ` (${item.detail})` : "";
    return `- ${item.label}: ${item.found ? "Found" : "Needs follow-up"}${detail}`;
  });
}

function renderCoverageHtml(result: ReviewResult): string {
  return `<div class="detail-grid">${coverageItems(result)
    .map(
      (item) => `<article class="detail">
        <strong>${escapeHtml(item.label)}</strong>
        <p>${item.found ? "Found" : "Needs follow-up"}</p>
        ${item.detail ? `<p class="muted">${escapeHtml(item.detail)}</p>` : ""}
      </article>`
    )
    .join("")}</div>`;
}

function coverageItems(result: ReviewResult): Array<{ label: string; found: boolean; detail?: string }> {
  const signals = result.evidence.signals;
  if (!signals) {
    return [{ label: "Public detail extraction", found: false, detail: "Not available for this review" }];
  }
  const contactFormsFound = countContactForms(result);
  const sitemap = result.evidence.sitemap;
  const registration = result.evidence.domainRegistration;
  const external = result.evidence.externalEvidence;
  const homepageLastModified = result.evidence.pages[0]?.lastModified;

  const pageDetail = (key: keyof typeof signals.pagePresence) => signals.pagePresenceDetails[key];
  const hasLinkedOrReviewedPage = (key: keyof typeof signals.pagePresence) => {
    const detail = pageDetail(key);
    return Boolean(detail?.sources.includes("linked") || detail?.sources.includes("reviewed_page"));
  };
  const pageDetailText = (key: keyof typeof signals.pagePresence) => {
    const detail = pageDetail(key);
    if (!detail) {
      return undefined;
    }
    return detail.urls.slice(0, 2).join(" | ") || detail.sources.map((source) => source.replace(/_/g, " ")).join(", ");
  };

  return [
    { label: "Contact page link", found: hasLinkedOrReviewedPage("contact"), detail: pageDetailText("contact") },
    { label: "Privacy Policy link", found: hasLinkedOrReviewedPage("privacy"), detail: pageDetailText("privacy") },
    { label: "Terms page link", found: hasLinkedOrReviewedPage("terms"), detail: pageDetailText("terms") },
    { label: "About page link", found: hasLinkedOrReviewedPage("about"), detail: pageDetailText("about") },
    { label: "Refund or return page link", found: hasLinkedOrReviewedPage("refund"), detail: pageDetailText("refund") },
    { label: "Shipping or delivery page link", found: hasLinkedOrReviewedPage("shipping"), detail: pageDetailText("shipping") },
    { label: "Cancellation page link", found: hasLinkedOrReviewedPage("cancellation"), detail: pageDetailText("cancellation") },
    { label: "Email address", found: signals.emails.length > 0, detail: signals.emails.slice(0, 2).join(", ") },
    { label: "Phone number", found: signals.phones.length > 0, detail: signals.phones.slice(0, 2).join(", ") },
    {
      label: "Address-like line",
      found: signals.addressLines.length > 0,
      detail: signals.addressLines.slice(0, 1).join(", ")
    },
    {
      label: "Social profile link",
      found: signals.socialLinks.length > 0,
      detail: signals.socialLinks.slice(0, 2).map((link) => `${link.label}: ${link.url}`).join(" | ")
    },
    {
      label: "Contact form",
      found: contactFormsFound > 0,
      detail: contactFormsFound > 0 ? `${contactFormsFound} found` : undefined
    },
    {
      label: "Sitemap",
      found: Boolean(sitemap?.found),
      detail: sitemap ? `${sitemap.status ? `HTTP ${sitemap.status}` : "not available"}; ${sitemap.pageUrls.length} page URL${sitemap.pageUrls.length === 1 ? "" : "s"}` : undefined
    },
    {
      label: "Domain registration dates",
      found: registration?.status === "found" && Boolean(registration.creationDate),
      detail: registration
        ? registration.creationDate
          ? `Created ${registration.creationDate}${registration.lastChangedDate ? `; changed ${registration.lastChangedDate}` : ""}`
          : formatDomainRegistrationStatus(result)
        : undefined
    },
    {
      label: "Homepage last modified",
      found: Boolean(homepageLastModified),
      detail: homepageLastModified ? formatPageLastModified(homepageLastModified) : undefined
    },
    {
      label: "Manual business registration state",
      found: Boolean(result.evidence.input.expectedState),
      detail: result.evidence.input.expectedState
    },
    {
      label: "State registry follow-up link",
      found: Boolean(external?.registryChecks.length),
      detail: external?.registryChecks.map((registry) => `${registry.state}: ${registry.searchUrl}`).join(" | ")
    },
    {
      label: "External public search links",
      found: Boolean(external?.searchLinks.length),
      detail: external ? `${external.searchLinks.length} generated` : undefined
    },
    {
      label: "Website-discovered external profiles",
      found: Boolean(external?.profileLinks.length),
      detail: external?.profileLinks.slice(0, 2).map((profile) => `${profile.platform}: ${profile.url}`).join(" | ")
    }
  ];
}

function renderSignalsMarkdown(result: ReviewResult): string[] {
  const signals = result.evidence.signals;
  if (!signals) {
    return ["- Public detail extraction was not available for this review."];
  }

  const commonPages = (Object.entries(signals.pagePresence) as Array<[keyof typeof signals.pagePresence, boolean]>)
    .filter(([, present]) => present)
    .map(([name]) => name);

  return [
    `- Emails: ${signals.emails.length ? signals.emails.join(", ") : "none found"}`,
    `- Phones: ${signals.phones.length ? signals.phones.join(", ") : "none found"}`,
    `- Contact forms: ${countContactForms(result)}`,
    `- Address-like lines: ${signals.addressLines.length ? signals.addressLines.join(" | ") : "none found"}`,
    `- Common pages: ${commonPages.length ? commonPages.map((name) => formatPresence(name, signals.pagePresenceDetails[name])).join(" | ") : "none found"}`,
    `- Social links: ${
      signals.socialLinks.length
        ? signals.socialLinks.map((link) => `${link.label}: ${link.url}`).join(" | ")
        : "none found"
    }`
  ];
}

function renderSignalsHtml(result: ReviewResult): string {
  const signals = result.evidence.signals;
  if (!signals) {
    return `<p class="muted">Public detail extraction was not available for this review.</p>`;
  }

  const commonPages = (Object.entries(signals.pagePresence) as Array<[keyof typeof signals.pagePresence, boolean]>)
    .filter(([, present]) => present)
    .map(([name]) => name);

  return `<div class="detail-grid">
    ${renderDetail("Emails", signals.emails)}
    ${renderDetail("Phones", signals.phones)}
    ${renderDetail("Contact Forms", [`${countContactForms(result)} found`])}
    ${renderDetail("Address-Like Lines", signals.addressLines)}
    ${renderDetail("Common Pages", commonPages.map((name) => formatPresence(name, signals.pagePresenceDetails[name])))}
    ${renderDetail(
      "Social Links",
      signals.socialLinks.map((link) => `${link.label}: ${link.url}`)
    )}
  </div>`;
}

function renderDetail(label: string, values: string[]): string {
  return `<article class="detail">
    <strong>${escapeHtml(label)}</strong>
    ${
      values.length
        ? `<ul>${values.slice(0, 8).map((value) => `<li>${escapeHtml(value)}</li>`).join("")}</ul>`
        : `<p class="muted">None found</p>`
    }
  </article>`;
}

function countContactForms(result: ReviewResult): number {
  return result.evidence.pages.reduce((total, page) => total + (page.forms?.contactFormCount ?? 0), 0);
}

function formatPresence(name: string, detail?: { sources: string[]; urls: string[] }): string {
  if (!detail) {
    return name;
  }
  const sources = detail.sources.map((source) => source.replace(/_/g, " ")).join(", ");
  return `${name} (${sources || "found"})`;
}

function renderList(items: string[]): string {
  return `<ul>${items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;
}

function bulletList(items: string[]): string[] {
  return items.map((item) => `- ${item}`);
}

function formatConcern(concern: ReviewConcern): string {
  const page = concern.pageUrl ? ` (${concern.pageUrl})` : "";
  const evidence = concern.evidence ? ` Evidence: ${concern.evidence}` : "";
  const label = concern.label ? `${concern.label}: ` : "";
  return `[${concern.severity}] ${label}${concern.message}${page}.${evidence}`;
}

function severityRank(severity: ReviewConcern["severity"]): number {
  switch (severity) {
    case "high":
      return 3;
    case "medium":
      return 2;
    case "low":
      return 1;
  }
}

function groupConcerns(concerns: ReviewConcern[]): Array<[ConcernArea, ReviewConcern[]]> {
  const order: ConcernArea[] = ["page_quality", "content_quality", "business_identity", "policy_pages", "commercial_behavior"];
  return order
    .map((area): [ConcernArea, ReviewConcern[]] => [area, concerns.filter((concern) => concern.area === area)])
    .filter(([, groupedConcerns]) => groupedConcerns.length > 0);
}

function areaLabel(area: ConcernArea): string {
  switch (area) {
    case "page_quality":
      return "Page Loading And Links";
    case "content_quality":
      return "Content Quality";
    case "business_identity":
      return "Business Details";
    case "policy_pages":
      return "Common Policy Pages";
    case "commercial_behavior":
      return "Commercial Behavior";
  }
}

function readableHost(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}

function evidencePathBase(screenshotPath: string): string {
  return path.dirname(path.dirname(screenshotPath));
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttribute(value: string): string {
  return escapeHtml(value);
}
